name: 'Publish family website to Github Pages'

on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/workflows/composite/build_dev
      - name: Black
        run: |
          source .venv/bin/activate       
          black --check --diff src/
  
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/workflows/composite/build_dev
      - name: Ruff
        run: |
          source .venv/bin/activate       
          ruff src/

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/workflows/composite/build_dev
      - name: MyPy
        run: |
          source .venv/bin/activate       
          mypy src/
  
  pytest:
    runs-on: ubuntu-latest
    needs:
      - black
      - ruff
      - mypy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/workflows/composite/build_dev
      - name: PyTest
        run: |
          source .venv/bin/activate
          pytest --cov=src --cov-report=json
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
  bandit:
    runs-on: ubuntu-latest
    needs:
      - black
      - ruff
      - mypy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/workflows/composite/build_dev
      - name: Bandit
        run: |
          source .venv/bin/activate
          bandit -r src/
      
  publish:
    runs-on: ubuntu-latest
    needs:
      - pytest
      - bandit
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/workflows/composite/build_prod    
      - name: Create page content
        run: |
          source .venv/bin/activate
          cd src
          pelican content -s core/settings.py -o ~/public
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ~/public
