name: 'Publish family website to Github Pages'

on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Checkout repository
        uses: actions/checkout@v3
      - name: ðŸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: ðŸ’¾ Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --only dev
      - name: ðŸ‘ŒðŸ» Check linters
        run: |   
          source .venv/bin/activate       
          black --check --diff src/
          ruff src/
          mypy src/
      
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: âœ… Checkout repository
        uses: actions/checkout@v3
      - name: ðŸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: ðŸ’¾ Install dependencies
        run: |
          echo "PYTHONPATH=$PYTHONPATH:./src" >> $GITHUB_ENV
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --without dev          
      - name: ðŸŒŸ Create page content
        run: |
          source .venv/bin/activate
          cd src
          pelican content -s core/settings.py -o ~/public
      - name: ðŸš€ Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ~/public
